import type { Request, Response } from "express";

export function funcpinsrequestid(req: Request, res: Response) {
  // N.b. unclear what call this comes from. It has been autogenerated by oas-tools
  res
    .status(456)
    .setHeader("content-type", "application/json")
    .send({
      error: {
        reason: "Not implemented for ipfs-search.com queue-pinservice",
        details:
          "This pinning service implementation can only use POST /pins/ to push pins to the search queue",
      },
    });
}

export function getPinByRequestId(req: Request, res: Response) {
  res
    .status(456)
    .setHeader("content-type", "application/json")
    .send({
      error: {
        reason: "GET /pins/{requestid} Not implemented for ipfs-search.com queue-pinservice",
        details:
          "This pinning service implementation can only use POST /pins/ to push pins to the search queue",
      },
    });
}

export function replacePinByRequestId(req: Request, res: Response) {
  res
    .status(456)
    .setHeader("content-type", "application/json")
    .send({
      error: {
        reason: "Unused function",
      },
    });
}

export function deletePinByRequestId(req: Request, res: Response) {
  res
    .status(456)
    .setHeader("content-type", "application/json")
    .send({
      error: {
        reason: "DELETE /pins/{requestid} Not implemented for ipfs-search.com queue-pinservice",
        details:
          "This pinning service implementation can only use POST /pins/ to push pins to the search queue",
      },
    });
}
